<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\db\Expression;

/**
 * This is the model class for table "expense".
 *
 * @property int $id
 * @property string $name
 * @property int $source
 * @property float $amount
 * @property string $month
 * @property string $expenseDate
 * @property int $createdAt
 * @property int $isPaid
 */
class Expense extends ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    //isPaid data will be mapped to this constant in view page
    const IS_PAID = [0 => 'Unpaid', 1 => 'Paid'];

    public static function tableName()
    {
        return 'expense';
    }


    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['createdAt'],
                    //ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
                // if you're using datetime instead of UNIX timestamp:
                //'value' => new Expression('NOW()'),
            ],

            [
                'class' => TimestampBehavior::class,
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['expenseDate'],
                ],
                // if you're using datetime instead of UNIX timestamp:
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            //TODO: name must be valid name. No special or numeric characters can be added
            [['name', 'amount'], 'required', 'on' => ['create', 'account']],
            [['amount'], 'required', 'on' => ['modify']],
            [['source', 'createdAt', 'isPaid'], 'integer'],
            [['amount'], 'number', 'min' => 100],
            //[['name'], 'match', 'pattern' => '^[a-zA-Z]+$','skipOnError' => true],
            [['name'], 'string', 'max' => 255],
            [['month'], 'default', 'value' => date('F')]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'source' => 'Source',
            'amount' => 'Amount',
            'month' => 'Month',
            'expenseDate' => 'Expense Date',
            'createdAt' => 'Created At',
            'isPaid' => 'Is Paid',
        ];
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
    }


}
